trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SPRING_PROFILES_ACTIVE: 'prod'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '--batch-mode'
        mavenOptions: '-Xmx1024m'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '$(JAVA_HOME_11_X64)'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
    - script: |
        mvn test
      displayName: 'Run tests'

- stage: Deploy
  dependsOn: Test
  jobs:
  - deployment: Deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '11'
              jdkArchitectureOption: 'x64'
          - script: |
              mvn spring-boot:run
            displayName: 'Deploy Spring Boot Application'
